# ros2 launch nav2_bringup nav2_navigation_launch.py params_file:=/home/lukic/ros2_tooling/src/webots_ros2/webots_ros2_epuck/resource/nav2_params.yaml

bt_navigator:
  ros__parameters:
    use_sim_time: True
    bt_xml_filename: "navigate_w_replanning_and_recovery.xml"
    plugin_lib_names:
      - nav2_compute_path_to_pose_action_bt_node
      - nav2_follow_path_action_bt_node
      - nav2_back_up_action_bt_node
      - nav2_spin_action_bt_node
      - nav2_wait_action_bt_node
      - nav2_clear_costmap_service_bt_node
      - nav2_is_stuck_condition_bt_node
      - nav2_goal_reached_condition_bt_node
      - nav2_initial_pose_received_condition_bt_node
      - nav2_reinitialize_global_localization_service_bt_node
      - nav2_rate_controller_bt_node
      - nav2_recovery_node_bt_node
      - nav2_pipeline_sequence_bt_node

bt_navigator_rclcpp_node:
  ros__parameters:
    use_sim_time: True

controller_server:
  ros__parameters:
    BaseObstacle:
      scale: 0.06
      sum_scores: false
    BaseObstacle/class: BaseObstacle
    GoalAlign:
      aggregation_type: last
      scale: 0.0
    GoalAlign/class: GoalAlign
    GoalDist:
      aggregation_type: last
      scale: 24.0
    GoalDist/class: GoalDist
    Oscillation:
      scale: 1.0
      x_only_threshold: 0.05
    Oscillation/class: Oscillation
    PathAlign:
      aggregation_type: last
      scale: 0.0
    PathAlign/class: PathAlign
    PathDist:
      aggregation_type: last
      scale: 0.0
    PathDist/class: PathDist
    RotateToGoal:
      scale: 32.0
    RotateToGoal/class: RotateToGoal
    acc_lim_theta: 3.2
    acc_lim_x: 2.5
    acc_lim_y: 0.0
    controller_frequency: 20.0
    critics:
    - RotateToGoal
    - Oscillation
    - BaseObstacle
    - GoalAlign
    - PathAlign
    - PathDist
    - GoalDist
    debug_trajectory_details: true
    decel_lim_theta: -1.2
    decel_lim_x: -0.5
    decel_lim_y: 0.0
    discretize_by_time: false
    goal_checker_name: dwb_plugins::SimpleGoalChecker
    local_controller_plugin: dwb_core::DWBLocalPlanner
    max_speed_xy: 0.04
    max_vel_theta: 1.0
    max_vel_x: 0.04
    max_vel_y: 0.0
    min_speed_theta: 0.0
    min_speed_xy: 0.0
    min_theta_velocity_threshold: 0.001
    min_vel_x: 0.0
    min_vel_y: 0.0
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.5
    prune_distance: 1.0
    prune_plan: true
    publish_cost_grid_pc: false
    publish_evaluation: true
    publish_global_plan: true
    publish_local_plan: true
    publish_trajectories: true
    publish_transformed_plan: true
    sim_time: 1.7
    trajectory_generator_name: dwb_plugins::StandardTrajectoryGenerator
    transform_tolerance: 0.02
    use_sim_time: true
    vx_samples: 10
    vy_samples: 5
    xy_goal_tolerance: 0.025
    yaw_goal_tolerance: 0.25
    short_circuit_trajectory_evaluation: True
    trans_stopped_velocity: 0.0025
    slowing_factor: 2.0
    lookahead_time: -1.0
    stateful: True

controller_server_rclcpp_node:
  ros__parameters:
    use_sim_time: True

local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 20.0
      publish_frequency: 10.0
      robot_base_frame: base_link
      use_sim_time: True
      global_frame: odom
      rolling_window: True
      width: 1
      height: 1
      resolution: 0.01
      transform_tolerance: 0.02
      plugin_names: ["obstacle_layer", "inflation_layer"]
      plugin_types:
        ["nav2_costmap_2d::ObstacleLayer", "nav2_costmap_2d::InflationLayer"]
      robot_radius: 0.035
      inflation_layer:
        cost_scaling_factor: 30.0
      obstacle_layer:
        enabled: true
        observation_sources: scan
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
      static_layer:
        map_subscribe_transient_local: True
      always_send_full_costmap: True
  local_costmap_client:
    ros__parameters:
      use_sim_time: True
  local_costmap_rclcpp_node:
    ros__parameters:
      use_sim_time: True

global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 1.0
      publish_frequency: 1.0
      robot_base_frame: base_link
      global_frame: map
      rolling_window: True
      use_sim_time: True
      plugin_names: ["static_layer", "obstacle_layer", "inflation_layer"]
      plugin_types:
        [
          "nav2_costmap_2d::StaticLayer",
          "nav2_costmap_2d::ObstacleLayer",
          "nav2_costmap_2d::InflationLayer",
        ]
      robot_radius: 0.035
      resolution: 0.01
      obstacle_layer:
        enabled: False
        observation_sources: scan
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
      static_layer:
        enabled: False
        map_subscribe_transient_local: True
      always_send_full_costmap: True
  global_costmap_client:
    ros__parameters:
      use_sim_time: True
  global_costmap_rclcpp_node:
    ros__parameters:
      use_sim_time: True

planner_server:
  ros__parameters:
    planner_plugin_types: ["nav2_navfn_planner/NavfnPlanner"]
    planner_plugin_ids: ["GridBased"]
    use_sim_time: True
    GridBased.tolerance: 0.0
    GridBased.use_astar: false
    GridBased.allow_unknown: true

planner_server_rclcpp_node:
  ros__parameters:
    use_sim_time: True

robot_state_publisher:
  ros__parameters:
    use_sim_time: True

recoveries_server:
  ros__parameters:
    costmap_topic: local_costmap/costmap_raw
    cycle_frequency: 10.0
    footprint_topic: local_costmap/published_footprint
    max_rotational_vel: 0.4
    min_rotational_vel: 0.2
    plugin_names:
    - Spin
    - BackUp
    - Wait
    plugin_types:
    - nav2_recoveries/Spin
    - nav2_recoveries/BackUp
    - nav2_recoveries/Wait
    rotational_acc_lim: 3.2
    simulate_ahead_time: 2.0
    use_sim_time: true