name: Bloom Release

on:
  release:
    types: [created]

jobs:
  bloom-release:
    runs-on: ubuntu-latest
    steps:
      - name: bloom release
        uses: DavidMansolino/bloom-release-action@v0.0.12
        with:
          ros_distro: eloquent foxy
          github_token_bloom: ${{ secrets.BLOOM_TOKEN }}
          github_user: DavidMansolino
          git_user: DavidMansolino
          git_email: David.Mansolino@cyberbotics.com
          release_repository_push_url: https://github.com/${{ github.repository }}-release.git
          version_branch: true 
          # open_pr: true
